
title: lilykiwi.github.io
email: lilykiwi9911@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Lily, a software engineer that loves to code. I'm currently studying Computer Science for Games at the University of Brighton.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lilykiwi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lilykiwi_
github_username:  lilykiwi
name: "Lily Rose"
repository: "lilykiwi/lilykiwi.github.io"
atom_feed:
  hide: true


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _global
  - scope:
      path: ""
    values:
      author_profile: true
      author: Lily
      layout: single
      share: true
      related: true
      toc: true
      paginate: 0
      sidebar:
        nav: "nav"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      read_time: true
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc_sticky: true
      toc: true
      comments: true
      share: true
      related: true


compress_html:
  clippings: all
  ignore:
    envs: development

minimal_mistakes_skin: "dark"
search: true

include: ["_pages"]

footer:
  links:
    - label: "Misskey"
      icon: "fab fa-fw fa-globe"
      url: "https://stop.voring.me/@lilykiwi"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lilykiwi_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lilykiwi"
