name: publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Init Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      -
        name: run 'npm install'
        run: npm install
      -
        name: run 'npm run build'
        run: npm run build
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
